"""updated city_id

Revision ID: 7b930cc91cea
Revises: abd4d1d55fbf
Create Date: 2023-08-02 15:20:09.462233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b930cc91cea'
down_revision = 'abd4d1d55fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usercity_city_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_usercity_city_id', ['city_id'])

    # ### end Alembic commands ###
