"""updated price

Revision ID: 9f7d5feb01bd
Revises: 1bc33af32dc0
Create Date: 2023-07-24 21:15:11.513551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9f7d5feb01bd'
down_revision = '1bc33af32dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_usd', sa.Float(), nullable=True))
        batch_op.drop_column('usd')
        batch_op.drop_column('avg')
        batch_op.drop_column('max')
        batch_op.drop_column('min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('max', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('avg', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('usd', sqlite.JSON(), nullable=True))
        batch_op.drop_column('avg_usd')

    # ### end Alembic commands ###
