"""edit user_id

Revision ID: abd4d1d55fbf
Revises: b50530403e9c
Create Date: 2023-07-31 17:40:52.298212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd4d1d55fbf'
down_revision = 'b50530403e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercities', schema=None) as batch_op:
        batch_op.drop_constraint('usercities', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercities', schema=None) as batch_op:
        batch_op.create_unique_constraint('usercities', ['user_id'])

    # ### end Alembic commands ###
