"""add usercity

Revision ID: b50530403e9c
Revises: e79a795b8cce
Create Date: 2023-07-31 17:20:39.904449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b50530403e9c"
down_revision = "e79a795b8cce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usercities", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_usercity_city_id", ["city_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usercities", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
