"""added blog table and other things

Revision ID: bc75e56ddf95
Revises: 17b60c79901f
Create Date: 2023-07-26 10:02:38.367180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc75e56ddf95'
down_revision = '17b60c79901f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('blog_body', sa.String(), nullable=True),
    sa.Column('blog_img', sa.String(), nullable=True),
    sa.Column('blog_city', sa.String(), nullable=True),
    sa.Column('blog_country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('img')

    op.drop_table('blogs')
    # ### end Alembic commands ###
