"""updated key

Revision ID: e79a795b8cce
Revises: bc2a8dc5cbcb
Create Date: 2023-07-31 17:14:24.755913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e79a795b8cce"
down_revision = "bc2a8dc5cbcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usercities", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("city_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_unique_constraint("usercities", ["city_id"])
        batch_op.create_unique_constraint("usercities", ["user_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usercities", schema=None) as batch_op:
        batch_op.drop_constraint("usercities", type_="unique")
        batch_op.drop_constraint("usercities", type_="unique")
        batch_op.alter_column("city_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
